### ISSUE TITLE
Empty tag prefix

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [anton-yurchenko/git-release#125]
### Description

How to match a version that does not use any tag prefix. Should I use `*`?

**Comment by anton-yurchenko** [comment]
As per the GitHub Actions workflow, you may use something like this:
```yml
on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
```
As per the action itself, it matches a semantic version with or without the `v` prefix.
You may control this behavior by defining the `TAG_PREFIX_REGEX` attribute.

**Comment by anton-yurchenko** [comment]
I don't understand the question.

> How to match a version that does not use any tag prefix

You need to customize nothing in that case:
```yaml
    - name: Release
      uses: docker://antonyurchenko/git-release:v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

> But what would be the regex for the prefix

You don't need to override the `TAG_PREFIX_REGEX` as its default value is `[v]?`. As you may see, the `v` letter is optional and not required by default.
