### ISSUE TITLE
Releasing from the first changelog entry

### ISSUE THREAD

**Issue by Fryuni** [anton-yurchenko/git-release#14]
### Description:  
Inconsistent generation of releases for the first changelog entry

### Tag:
`0.0.1-beta1`

### Workflow:
```
- name: Release
  uses: docker://antonyurchenko/git-release:v3
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    DRAFT_RELEASE: "true"
    PRE_RELEASE: "false"
    CHANGELOG_FILE: "CHANGELOG.md"
    ALLOW_EMPTY_CHANGELOG: "true"
    ALLOW_TAG_PREFIX: "false"
```

### Changelog:
```
# Changelog

## [0.0.1-beta1](https://github.com/croct-tech/plug-js/tree/0.0.1-beta1) (2020-03-22)

[Full Changelog](https://github.com/croct-tech/plug-js/compare/20cdc015ba4f2f5b2ec9881e9bd72ea09b6bc381...0.0.1-beta1)
```  

### Log:
```
WARNING 'ALLOW_EMPTY_CHANGELOG' enabled              
FATAL empty changelog for requested version: '0.0.1-beta1' 
```  

### Problem:
[This regex](https://github.com/anton-yurchenko/git-release/blob/dbe088c38fd005d5bd0b9f826a1e7f09d7affd13/pkg/changelog/private.go#L33) will match the line starting with `[Full Changelog]` and return one line above.

Is there a reason for this check before returning `len(content)`? This matching will cause all releases from a first entry that have any line starting with a link to have an incomplete body, and is not consistent with what would happen with multiple entries.  
With multiple entries like:
```
# Changelog

## [0.0.1-beta2](https://github.com/croct-tech/plug-js/tree/0.0.1-beta2) (2020-03-22)

[Full Changelog](https://github.com/croct-tech/plug-js/compare/0.0.1-beta1...0.0.1-beta2)

## [0.0.1-beta1](https://github.com/croct-tech/plug-js/tree/0.0.1-beta1) (2020-03-22)

Some message
[Full Changelog](https://github.com/croct-tech/plug-js/compare/20cdc015ba4f2f5b2ec9881e9bd72ea09b6bc381...0.0.1-beta1)
```
generating a release for the tag `0.0.1-beta2` will include the full changelog link on the release body, but would not on `0.0.1-beta1`
