### ISSUE TITLE
Wildcard or environment variables in args:

### ISSUE THREAD

**Issue by rsliotta** [anton-yurchenko/git-release#20]
This is more of a question:

I want to pass the version number or a wildcard the the args like this:
    env:
        RELEASE_VERSION="v0.1.2"
    args: |
            testpv.yaml
            bob-plugins-*.tgz
            bob-plugins-$RELEASE_NAME.tgz

This is simplified for an example of course.

The first fails for invalid syntax and the second does not expand variable

**Comment by anton-yurchenko** [comment]
If I understood you correctly, I believe you should be able to do one of the following:
```
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: "v0.1.2"
        with:
          args: |
            testpv.yaml
            bob-plugins-${{ env.RELEASE_VERSION }}.tgz
```
or alternatively get the version from tag directly:
```
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            testpv.yaml
            bob-plugins-${{ env.GITHUB_REF }}.tgz
```
You should be able to find more info [here](https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions)
