### ISSUE TITLE
Github Badge

### ISSUE THREAD

**Issue by rsliotta** [anton-yurchenko/git-release#23]
I am running my workflow and the last step is the git-release.  No matter what I do, badge for workflow is 'failing'.  Here is my workflow:

```
#Workflows
name: publish_release
on: 
  push:
    tags:
    - "v[0-9]+.[1-9]+.[0-9]*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - run: |
          export POSTFIX=" (Codename: '$(cat CODENAME)')"
          echo "::set-env name=RELEASE_NAME_POSTFIX::$POSTFIX"
      - name: Print Release Version
        run: |
          export RELEASE_VERSION=$(echo $GITHUB_REF | awk -F\/ '{print $3}')
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "Release Version is $RELEASE_VERSION"
          echo "$RELEASE_VERSION" > VERSION
      - name: Create Plugins
        run: |
          bash -c "chmod 755 ./plugins.sh; ./plugins.sh"
          bash -c "cd plugins/kubectl;  tar zcvf ../../bob-plugins-${{ env.RELEASE_VERSION }}.tgz *; cd ../.."
      - name: Build Action 
        env: # Or as an environment variable
            docker_login: ${{ secrets.DOCKER_ID }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}      
        run: |
          bash -c "chmod 755 files/*; chmod 644 files/*.conf files/README"
          bash -c "chmod 755 ./init.sh; LATEST=true TAG=$RELEASE_VERSION DOCKERFILE=dockerfiles/Dockerfile       ./init.sh bob-core"
          bash -c "chmod 755 ./init.sh; LATEST=true TAG=$RELEASE_VERSION DOCKERFILE=dockerfiles/Dockerfile.proxy ./init.sh bob-proxy"
          bash -c "chmod 755 ./init.sh; LATEST=true TAG=$RELEASE_VERSION DOCKERFILE=dockerfiles/Dockerfile.mini  ./init.sh bob"
          bash -c "chmod 755 ./charts.sh; ./charts.sh"
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish'
          force-add: 'true'
          files: VERSION docs/index.yaml docs/*.tgz
          name: rsliotta
          email: bob@bobdot.me
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "docs/changes.md"
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |
            examples/testpv.yaml
            bob-plugins-${{ env.RELEASE_VERSION }}.tgz
            plugins/installer.sh
```
