### ISSUE TITLE
Accept build artifact name(s)

### ISSUE THREAD

**Issue by reitzig** [anton-yurchenko/git-release#24]
### Description:  

It seems prudent to assemble release assets using [build artifacts](https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts). In particular, we may use separate jobs for different assets, e.g. using a build matrix, so we will never have all assets in the same working directory (without further work).

`git-release` should accept names of build artifacts, and internally download the included files.
I can think of two ways to do this (short of re-wrapping the action as JS action, which seems to open up possibilities for richer user interfaces than Docker actions):

#### Option A: 

Arguments can be either:

```yaml
- uses: docker://antonyurchenko/git-release:v3
  with:
    args: |
      Release Assets
      some-other-file.md
```

_Problem:_ What if artifact and workspace file names conflict?

#### Option B: Addition environment variable

```yaml
- uses: docker://antonyurchenko/git-release:v3
  env:
    RELEASE_ARTIFACT: "Release Assets"
  args: |
      some-other-file.md
```

_Problem:_ Doesn't scale well to multiple artifacts.

### Workaround

Download the artifact and list its content manually:

```yaml
- uses: actions/download-artifact@v2
  with:
    name: "Release Assets"
    path: "release_assets"

- id: asset_names
  run: echo ::set-output name=LIST::$(find release_assets)

- uses: docker://antonyurchenko/git-release:v3
  with:
    args: "${{ steps.asset_names.outputs.LIST }}"
```

See something similar in action [here](https://github.com/reitzig/container-do/blob/master/.github/workflows/release.yml).

**Comment by anton-yurchenko** [comment]
I understand your point, and to be honest, I think its kind of a common need to collect artifacts from different parallel stages.

I believe that each action should take care of a certain task, and only that small task in order to be simple, generic, and reliable.

That matrix that you are describing looks like a usecase for another Action to be made 🙂 an alternative to **actions/download-artifact** 😉

That artifact preparing action has enough to take care of like filename collisions, multiple artifacts download, moving files around and preparing a file tree, maybe even creating archives and cleaning the GitHub Artifacts in order to lower the Packages billing, and more...

Moreover, independent action will also simplify the matrix definition as it will have clean `args` and `env` that may be used for that.

**Comment by reitzig** [comment]
I _think_ you've misunderstood my request because I can't make heads nor tails of your response. :sweat_smile: 

My problem isn't with assembling the artifact(s), that's well taken care of and I give it for background.
The issue is that I can't tell `git-release` to _use_ any artifact I've assembled.

Note that wildcards like `args: "my-asset_*_.tar.gz` also doesn't work. That would be another alternative to consider, but the real goal here is to get rid of `download-artifact`+hack.

**Comment by anton-yurchenko** [comment]
Uhm I got you, my bad!
I will add wildcard support in the next release.

As per artifacts download, it sure looks like a good addition that should be implemented.
I think the following pattern might work:
```
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: |                   # <artifact-name>:<filename-pattern>
            job1:release/app.exe    # single file from artifact
            job2:build/*.dll        # wildcard matching in an artifact
            job3:*                  # every file from an artifact
            LICENSE.md              # file from current workspace
            *.jpg                   # wildcard matching in current workspace
```

**Comment by anton-yurchenko** [comment]
Unfortunately, *download artifacts* seems to be problematic for implementation.
The reason for that is that artifacts are not available during a workflow run through [API](https://developer.github.com/v3/actions/artifacts/#list-workflow-run-artifacts), but only after it finishes.

*Going through a code of an official [actions/download-artifact](https://github.com/actions/download-artifact), I have noticed that it uses a different API and auth.
**git-release** may mimic this by crafting an API calls that will look similar to:
`https://pipelines.actions.githubusercontent.com/<actions-token>/_apis/pipelines/workflows/<workflow-run>/artifacts?api-version=6.0-preview`
But it will break without a notice* ❗ 

Thus, we will have to rely on other steps to prepare the files for a release, with something like:
```yaml
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      [...]

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: build/linux-amd64

  job-2:
    runs-on: macos-latest
    steps:
      [...]

      - uses: actions/upload-artifact@v2
        with:
          name: darwin
          path: build/darwin-amd64
  
  job-3:
    runs-on: windows-latest
    steps:
      [...]

      - uses: actions/upload-artifact@v2
        with:
          name: darwin
          path: build/windows-amd64.exe

  release:
    needs: [job-1, job-2, job-3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux
          path: artifacts
      
      - uses: actions/download-artifact@v2
        with:
          name: macos
          path: artifacts
      
      - uses: actions/download-artifact@v2
        with:
          name: windows
          path: artifacts

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: none
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: artifacts/build/*-amd64*
```
