### ISSUE TITLE
Support a "Unreleased" pre-release

### ISSUE THREAD

**Issue by cb80** [anton-yurchenko/git-release#47]
Hello @anton-yurchenko

### Description
https://keepachangelog.com/ defines the `Unreleased` section. I propose to create/update/replace a pre-release whenever a specific tag is updated e.g. a `latest` tag? As a pre-release it is identified as non-production ready. Also the latest tag is potentially moved with every merge to the main branch.

The benefit from my point of view is that you can automatically deliver something users can test with.

This is how it could be used:
```
on:
  push:
    tags:
    - 'latest'

...

    - name: Latest Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "true"
        CHANGELOG_FILE: "CHANGELOG.md"
        CHANGELOG_SECTION: "Unreleased"
        ALLOW_EMPTY_CHANGELOG: "false"
      with:
        args: |
            build/*-amd64.zip
```

What do you think about that?

PS: From the docs: `Note: The release event is not triggered for draft releases.`

### Reference
- https://keepachangelog.com/
- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release
