### ISSUE TITLE
[QUESTION] How to do prerelease like on suffix?

### ISSUE THREAD

**Issue by Muizz-DS** [anton-yurchenko/git-release#50]
### Description
In your example, you do the prerelease like `prerelease-1.0.0`. So, I have question on how to do a pre-release like `v1.0.0-alpha` based on your configuration? This is more following the semVer guideline. Hope that you can give the suggestion on how to do it with this Action.

Thumbs up👍 for the contibution. It helps me a lot!😀

### Reference
- [Semantic Versioning](https://semver.org/spec/v2.0.0.html)

**Comment by anton-yurchenko** [comment]
Hello @Muizz-DS,
Actually, you need to configure nothing in that case as your tag is a valid sematic version.

*You might need to enable `ALLOW_EMPTY_CHANGELOG` as you probably won't have changes for such a releases like `rc`/`beta`/`alpha` in your changelog file.*

### Sample Workflow

```yaml
name: example

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-alpha**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ALLOW_EMPTY_CHANGELOG: "true"
        with:
          args: |
            artifacts/linux-assets.zip
            artifacts/windows-assets.zip
```

### Execution

![image](https://user-images.githubusercontent.com/33016810/122338557-8f144f80-cf48-11eb-855b-ba3e873dda12.png)
