### ISSUE TITLE
How to restict folders and files for the Release?

### ISSUE THREAD

**Issue by treee111** [anton-yurchenko/git-release#52]
Hi,

I do not want to include all files of my repo into the release .zip file.
Is this possible with your plugin?

I tried the following already to only have files of the `common_resources` folder in the created release .zip files but each time it copied everything from the repository into the .zip files:

```
name: Git Release

on:
  push:
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME_PREFIX: "Release "
        with:
          args: common_resources/*
```

and 
```
        with:
          args: |
            common_resources/*.zip
```

and 
```
        with:
          args: |
            common_resources/*
```

**Comment by anton-yurchenko** [comment]
Hello @treee111,
There are two archives created by default on GitHub which contain a source code for that ref and cannot be removed:
![image](https://user-images.githubusercontent.com/33016810/126880837-b0f853fc-467f-4524-b5ff-ba0f2f5eaef4.png)

The rest are optional artifacts that you might attach to the release. The following instruction will add all ZIP files in a `common_resources` directory:
```
        with:
          args: |
            common_resources/*.zip
```

Here is an example for the previously attached screenshot:

```yaml
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: dist/version-bump-*
```

Did I understand you correctly? You are talking about the **Source Code Archives** right? *(in case not, please provide a screenshot of a release created with a configuration you have provided earlier)*
