### ISSUE TITLE
Regression in v4.2+

### ISSUE THREAD

**Issue by kongsgard** [anton-yurchenko/git-release#61]
### Description
Thanks for providing such a useful action!
There seems to be a regression introduced in v4.2.0, as the action does not work for this version or v4.2.1. I get the following output:

```
INFO release created successfully 🎉               
INFO uploading asset                               asset=asset.zip
WARNING error uploading asset: Post "https://uploads.github.com/[...]": read tcp xxx.xx.xxx.xx:xxx->yyy.yy.yyy.yy:yyy: read: connection reset by peer  asset=asset.zip
INFO retrying (2/4) uploading asset in 9 seconds   asset=asset.zip
```

This is retried four times.
The release is added, but the assets are not uploaded.

If I revert to v.4.1.2, the action works as intended.
This is for a private repository.

### Tag
v4.2.0 and v4.2.1

### Workflow
(This is added after a build job.)
```
release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: build
      - run: zip -r asset.zip Build
        working-directory: ./build
      - name: Release
        uses: docker://antonyurchenko/git-release:v4.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRE_RELEASE: "true"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
          RELEASE_NAME_PREFIX: "Release: "
        with:
          args: |
            ./build/*.zip
```
