### ISSUE TITLE
add in documenation: UNRELEASED and DRAFT_RELEASE do not work together

### ISSUE THREAD

**Issue by treee111** [anton-yurchenko/git-release#90]
### Why this issue?
I don't know how I came to that configration and if it worked earlier or not.
Lately I saw it not updating the `latest` release and it took me some time to figure out what causes this issue.
The errormessages, in my opinion, did not lead to the misconfiguration. That's why I want to inform you about that, if you have a place for that to be documented, feel free to do so!

### Description
`UNRELEASED: "update"` together with `DRAFT_RELEASE: true` does not work after the first time.
It works the first time but seams that the created draft-release can not be changed by the action on the second and all further runs.

- non-working workflow configuration:
```
- name: Release
  uses: docker://antonyurchenko/git-release:latest
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    UNRELEASED: "update"
    ALLOW_EMPTY_CHANGELOG: true
    DRAFT_RELEASE: true
```

- working workflow configuration:
```
- name: Release
  uses: docker://antonyurchenko/git-release:latest
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    UNRELEASED: "update"
    ALLOW_EMPTY_CHANGELOG: true
```

### Reference
- non-working workflow configuration:
https://github.com/treee111/wahooMapsCreator/actions/runs/4098103949

- working workflow configuration:
https://github.com/treee111/wahooMapsCreator/actions/runs/4098160692

- my PR to correct it in my repo:
https://github.com/treee111/wahooMapsCreator/pull/178
